version: '3.8'
volumes:
  postgres_data:
  regulus-attachments:
  seq-data:
  redis_data:
services:
  regulus-application-core:
    image: regulus-application-core
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TZ=Asia/Bangkok
      - DefaultConnection=Host=postgres;Database=regulus-db;Username=admin;Password=P@ssw0rd;
      - HangfireConnection=Host=postgres;Database=regulus-db;Username=admin;Password=P@ssw0rd;
    ports:
      - "8800:8080"
    volumes:
      - regulus-attachments:/regulus-attachments
    depends_on:
      - postgres

  postgres:
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: regulus-db
      TZ: Asia/Bangkok
      PGTZ: Asia/Bangkok
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  # regulus-client-app:
  #   container_name: regulus-client-app
  #   image: regulus-client-app
  #   build:
  #     context: .
  #     dockerfile: ./src/client_web/docker/Dockerfile
  #     args:
  #       - VITE_API_BACKEND_URL=http://dev.reguluscloud.com:8888
  #   ports:
  #     - 8098:8888

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    # command: ["redis-server", "--requirepass", "P@ssw0rd"]
    volumes:
      - redis_data:/data

  seq:
    image: datalust/seq:latest
    container_name: seq
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "seqP@ssw0rd"
    ports:
      - "5341:80"
    volumes:
      - seq-data:/data
      
  nginx:
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - 8081:8081
    build:
      context: .
      dockerfile: ./nginx/docker/dockerfile
    volumes: 
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf